### ISSUE TITLE
Linker error after wifi was removed

### ISSUE THREAD

**Issue by JojoS62** [mbed-ce/mbed-os#251]
the PR #247 removed some stuff, now I'm getting a linker error with my custom target F407. The previous version was building without error.

linker message:
```
[build] /opt/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/13.2.1/../../../../arm-none-eabi/bin/ld: cannot find -lmbed-wifi: No such file or directory
[build] collect2: error: ld returned 1 exit status
[build] ninja: build stopped: subcommand failed.
```

mbed_wifi is not pulled in by the macro create_mbed_wifi_target, I'm trying to find where it gets referenced. 
--> mbed-wifi is added by connectivity/netsocket

When mbed-wifi is excluded in netsocket, the code compiles and is working. So probably it could be removed? I don't have the overview yet.

**Comment by multiplemonomials** [comment]
Oops, try #252
