### ISSUE TITLE
Configuration of mbed os may be useful 

### ISSUE THREAD

**Issue by wubaojun1982** [mbed-ce/mbed-os#297]
In my past development, there are many problems from configuration. In the zephyr or rt-thread rtos system, they used Kconfig as system configuration. So i think we can used Kconfig tools as the system configuration tools. Thanks very much.

**Comment by JohnK1987** [comment]
Hello,

from my point of view this is not an issue and should be discussed in https://github.com/mbed-ce/mbed-os/discussions/categories/ideas

When i look on Zephyr's description of the kconfig then i see similar/same what do the configuration system in Mbed via .json files and cmake.
So what are differences? I suppose you did a comparison so would be good to share your findings as arguments.

BR, Jan

**Comment by JohnK1987** [comment]
No more reactions plus this is not an issue but an idea.
Next time please use https://github.com/mbed-ce/mbed-os/discussions/categories/ideas but it is necessary to come with some comparison, with the expected benefits why we should choose to the kconfig. Not just a wish.

Thank you for understanding.
