### ISSUE TITLE
Does mbed-ce supports development boards which have been supported by mbed-os?

### ISSUE THREAD

**Issue by wubaojun1982** [mbed-ce/mbed-os#68]
https://os.mbed.com/platforms/
the development boads supported by mbed-os has 176  boards, such as 
https://os.mbed.com/platforms/ST-Nucleo-G474RE/
https://os.mbed.com/platforms/ST-Nucleo-L4R5ZI-P/
and so on.

**Comment by JohnK1987** [comment]
Hello @wubaojun1982 and welcome,

all boards supported on MbedOs6 should work here, but for boards what are not on [this list](https://github.com/mbed-ce/mbed-os/wiki/Mbed-CE-Officially-Supported-Targets-&-Features) you need manually add/create [config files](https://github.com/mbed-ce/mbed-os/tree/master/targets/upload_method_cfg) for Upload methods.

If you need any assistance let us know.

BR, Jan

**Comment by JohnK1987** [comment]
However, if you will build project according to (for example) [Project-Setup:-VS-Code](https://github.com/mbed-ce/mbed-os/wiki/Project-Setup:-VS-Code), you can set  the UPLOAD METHOD to NONE.

In `cmake-variants.yaml` file change
```
 // from
 UPLOAD_METHOD: YOUR_UPLOAD_METHOD
 // to
 UPLOAD_METHOD: NONE
```
Then the project will be builded and compiled, but not automatically uploaded and you need to upload the .bin file manually from BUILD folder.

BR, Jan

**Comment by wubaojun1982** [comment]
There is the second question.
How to add other libraries to mbed-ce? like this:
https://os.mbed.com/teams/PQ_Hybrid_Electrical_Equipment_Team/code/SHT31_DIS_lib/
https://os.mbed.com/teams/Akafugu/code/_24LCXXX/
I don't know how to edit the CMakeLists.txt. 
Maybe you can add Official Examples with more than two libraries in the github.

**Comment by multiplemonomials** [comment]
Adding a library like that should be fairly easy.  

First, copy the ` SHT31_DIS_lib` directory into your project top directory.

Then, edit the top-level CMakeLists.txt to have:
```
add_subdirectory(SHT31_DIS_lib)
```

Next, create a CMakeLists.txt in the SHT31_DIS_lib folder with the following content:
```cmake
set(SHT31_DS_SOURCES
    SHT3x.cpp)

add_library(SHT31_DS ${SHT31_DS_SOURCES})
target_include_directories(SHT31_DS PUBLIC .) # make sure the header is visible
target_link_libraries(SHT31_DS PUBLIC mbed-os) # Link to Mbed OS to get includes and defines
```

Finally, link the new library to your application in your top-level CMakeLists.txt:
```cmake
target_link_libraries(MyApp SHT31_DIS)
```

That procedure is pretty standard CMake and should work, let me know if it doesn't.  We should definitely look into creating a more detailed example to show working with multiple libraries...

**Comment by JohnK1987** [comment]
So @wubaojun1982  are you able to reproduce these steps?
An example will be added in the future, but it seems there will be also necessary some basic knowledge about CMake.

BR, Jan

**Comment by wubaojun1982** [comment]
Thanks. I will try it.

**Comment by JohnK1987** [comment]
Original question of this Issue was already answered. The another question is without any feedback for more than 7 days.
